# Generated by Django 2.1.5 on 2021-07-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_page_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
    ]
