# Generated by Django 2.1.5 on 2021-07-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_remove_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
